from funix import funix


@funix(
    title="09. 财务说明",
    input_layout=[
        [{"markdown": "**未来三年营收预测表**"}],
        [
            {"markdown": "项目"},
            {"markdown": "第一年"},
            {"markdown": "第二年"},
            {"markdown": "第三年"},
        ],
        [
            {"markdown": "**一、主营业务收入（不含税）**"},
            {"argument": "year_1_main_business_income_excluding_tax"},
            {"argument": "year_2_main_business_income_excluding_tax"},
            {"argument": "year_3_main_business_income_excluding_tax"},
        ],
        [
            {"markdown": "&emsp;&emsp;减：主营业务成本"},
            {"argument": "year_1_main_business_cost"},
            {"argument": "year_2_main_business_cost"},
            {"argument": "year_3_main_business_cost"},
        ],
        [
            {"markdown": "&emsp;&emsp;&emsp;&emsp;主营业务税金及附加"},
            {"argument": "year_1_main_business_tax_and_others"},
            {"argument": "year_2_main_business_tax_and_others"},
            {"argument": "year_3_main_business_tax_and_others"},
        ],
        [
            {"markdown": "二、主营业务利润（亏损以“-”号）"},
            {"argument": "year_1_main_business_profit"},
            {"argument": "year_2_main_business_profit"},
            {"argument": "year_3_main_business_profit"},
        ],
        [
            {"markdown": "&emsp;&emsp;加：其他业务利润（亏损以“-”号）"},
            {"argument": "year_1_other_business_profit"},
            {"argument": "year_2_other_business_profit"},
            {"argument": "year_3_other_business_profit"},
        ],
        [
            {"markdown": "&emsp;&emsp;减：营业费用"},
            {"argument": "year_1_operating_cost"},
            {"argument": "year_2_operating_cost"},
            {"argument": "year_3_operating_cost"},
        ],
        [
            {"markdown": "&emsp;&emsp;&emsp;&emsp;管理费用"},
            {"argument": "year_1_management_cost"},
            {"argument": "year_2_management_cost"},
            {"argument": "year_3_management_cost"},
        ],
        [
            {"markdown": "&emsp;&emsp;&emsp;&emsp;财务费用"},
            {"argument": "year_1_financial_cost"},
            {"argument": "year_2_financial_cost"},
            {"argument": "year_3_financial_cost"},
        ],
        [
            {"markdown": "三、营业利润（亏损以“-”号）"},
            {"argument": "year_1_business_profit"},
            {"argument": "year_2_business_profit"},
            {"argument": "year_3_business_profit"},
        ],
        [
            {"markdown": "**四、利润总额**"},
            {"argument": "year_1_profit_total"},
            {"argument": "year_2_profit_total"},
            {"argument": "year_3_profit_total"},
        ],
        [
            {"markdown": "&emsp;&emsp;减：所得税"},
            {"argument": "year_1_tax"},
            {"argument": "year_2_tax"},
            {"argument": "year_3_tax"},
        ],
        [
            {"markdown": "**五、净利润**"},
            {"argument": "year_1_net_profit"},
            {"argument": "year_2_net_profit"},
            {"argument": "year_3_net_profit"},
        ],
        [{"markdown": "**未来三年费用预测表**"}],
        [
            {"markdown": "年份"},
            {"markdown": "研发"},
            {"markdown": "市场"},
            {"markdown": "产品"},
            {"markdown": "行政"},
            {"markdown": "设备"},
            {"markdown": "其他"},
        ],
        [
            {"markdown": "第一年"},
            {"argument": "year_1_rnd"},
            {"argument": "year_1_market"},
            {"argument": "year_1_product"},
            {"argument": "year_1_govern"},
            {"argument": "year_1_equipment"},
            {"argument": "year_1_other"},
        ],
        [
            {"markdown": "第二年"},
            {"argument": "year_2_rnd"},
            {"argument": "year_2_market"},
            {"argument": "year_2_product"},
            {"argument": "year_2_govern"},
            {"argument": "year_2_equipment"},
            {"argument": "year_2_other"},
        ],
        [
            {"markdown": "第三年"},
            {"argument": "year_3_rnd"},
            {"argument": "year_3_market"},
            {"argument": "year_3_product"},
            {"argument": "year_3_govern"},
            {"argument": "year_3_equipment"},
            {"argument": "year_3_other"},
        ],
    ],
    argument_labels={
        (
            "year_1_main_business_income_excluding_tax",
            "year_1_main_business_cost",
            "year_1_main_business_tax_and_others",
            "year_1_main_business_profit",
            "year_1_other_business_profit",
            "year_1_operating_cost",
            "year_1_management_cost",
            "year_1_financial_cost",
            "year_1_business_profit",
            "year_1_profit_total",
            "year_1_tax",
            "year_1_net_profit",
            "year_2_main_business_income_excluding_tax",
            "year_2_main_business_cost",
            "year_2_main_business_tax_and_others",
            "year_2_main_business_profit",
            "year_2_other_business_profit",
            "year_2_operating_cost",
            "year_2_management_cost",
            "year_2_financial_cost",
            "year_2_business_profit",
            "year_2_profit_total",
            "year_2_tax",
            "year_2_net_profit",
            "year_3_main_business_income_excluding_tax",
            "year_3_main_business_cost",
            "year_3_main_business_tax_and_others",
            "year_3_main_business_profit",
            "year_3_other_business_profit",
            "year_3_operating_cost",
            "year_3_management_cost",
            "year_3_financial_cost",
            "year_3_business_profit",
            "year_3_profit_total",
            "year_3_tax",
            "year_3_net_profit",
            "year_1_rnd",
            "year_1_market",
            "year_1_product",
            "year_1_govern",
            "year_1_equipment",
            "year_1_other",
            "year_2_rnd",
            "year_2_market",
            "year_2_product",
            "year_2_govern",
            "year_2_equipment",
            "year_2_other",
            "year_3_rnd",
            "year_3_market",
            "year_3_product",
            "year_3_govern",
            "year_3_equipment",
            "year_3_other",
        ): "单位：万元"
    },
)
def project_financial_description(
    year_1_main_business_income_excluding_tax: float = 0.0,
    year_1_main_business_cost: float = 0.0,
    year_1_main_business_tax_and_others: float = 0.0,
    year_1_main_business_profit: float = 0.0,
    year_1_other_business_profit: float = 0.0,
    year_1_operating_cost: float = 0.0,
    year_1_management_cost: float = 0.0,
    year_1_financial_cost: float = 0.0,
    year_1_business_profit: float = 0.0,
    year_1_profit_total: float = 0.0,
    year_1_tax: float = 0.0,
    year_1_net_profit: float = 0.0,
    year_2_main_business_income_excluding_tax: float = 0.0,
    year_2_main_business_cost: float = 0.0,
    year_2_main_business_tax_and_others: float = 0.0,
    year_2_main_business_profit: float = 0.0,
    year_2_other_business_profit: float = 0.0,
    year_2_operating_cost: float = 0.0,
    year_2_management_cost: float = 0.0,
    year_2_financial_cost: float = 0.0,
    year_2_business_profit: float = 0.0,
    year_2_profit_total: float = 0.0,
    year_2_tax: float = 0.0,
    year_2_net_profit: float = 0.0,
    year_3_main_business_income_excluding_tax: float = 0.0,
    year_3_main_business_cost: float = 0.0,
    year_3_main_business_tax_and_others: float = 0.0,
    year_3_main_business_profit: float = 0.0,
    year_3_other_business_profit: float = 0.0,
    year_3_operating_cost: float = 0.0,
    year_3_management_cost: float = 0.0,
    year_3_financial_cost: float = 0.0,
    year_3_business_profit: float = 0.0,
    year_3_profit_total: float = 0.0,
    year_3_tax: float = 0.0,
    year_3_net_profit: float = 0.0,
    year_1_rnd: float = 0.0,
    year_1_market: float = 0.0,
    year_1_product: float = 0.0,
    year_1_govern: float = 0.0,
    year_1_equipment: float = 0.0,
    year_1_other: float = 0.0,
    year_2_rnd: float = 0.0,
    year_2_market: float = 0.0,
    year_2_product: float = 0.0,
    year_2_govern: float = 0.0,
    year_2_equipment: float = 0.0,
    year_2_other: float = 0.0,
    year_3_rnd: float = 0.0,
    year_3_market: float = 0.0,
    year_3_product: float = 0.0,
    year_3_govern: float = 0.0,
    year_3_equipment: float = 0.0,
    year_3_other: float = 0.0,
):
    pass
